//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SdNcenter.Dnks.Parameters;
using SdNcenter.Dnks.Executors;
using SdNcenter.Dnks.KnowledgeScripts;
using SdNcenter.Dnks.Responses;
using SdNcenter.Dnks.PowerShell.KnowledgeScripts;

namespace powerShellKSSecurityConfigurationManager
{
    [global::System.Runtime.InteropServices.ComVisible(true)]
    [global::System.Runtime.InteropServices.Guid("10e0b421-039e-4f9b-896d-c7240b926aa6")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.0.0.0")]
    public interface IMyScript1Parameters : IMyScript1ParametersLocal
    {
        [global::System.Runtime.InteropServices.DispId(1)]
        string MySampleInput { get; set; }

    }

    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.0.0.0")]
    public interface IMyScript1ParametersLocal
    {
        string MySampleInput { get; }

    }

    [global::System.Runtime.InteropServices.ComVisible(true)]
    [global::System.Runtime.InteropServices.Guid("76075655-d5c4-4a78-aae3-2ec51db4cc5a")]
    [global::System.Runtime.InteropServices.ClassInterface(global::System.Runtime.InteropServices.ClassInterfaceType.None)]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.0.0.0")]
    public sealed class MyScript1Parameters : KSParameters, IMyScript1Parameters
    {
        public string MySampleInput { get; set; }

    }

    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.0.0.0")]
    public partial class MyScript1 : PowerShellKnowledgeScriptBase<MyScript1Parameters, IMyScript1ParametersLocal, WindowsNqExt, IWindowsNqExt>
    {
        protected override string LicenseData
        {
            get { return "jXXyP5Ego8HhZxR4nCtLgOrLhpjJw4K4p7EVsnqNzojRMKTSdlLdND9x3DD3xvcI3wN7wOJhQ51qx6H3j+9RNlekMFOnny6OtrF0FX/kHkxzq+3nRCsKUzn/odM4VoRT"; }
        }
        
        protected override string DesKey
        {
            get { return "FmPeSuKS+bRKjiyt2Koaq4FnDIUOtGJCpBAx7SPbsjMrYqxPKdyezhLKN/aQDkml1ikbxU6XOlun67UyjYwlYkjR0+stmgVxT/hr4HW3nm1WL4vmosbZuwKW6gpdhIvID8EIk0v8yI66ItutSpiuLbsX5WY3wT1ljp8/elRjN4esr6mh4pfi+foNCTRnNc7KJqyJM/fdJkSowxJ17bmM/2Oqg9sRQvdPfwZ0Om5+86/jW6QxbDQIcGZOQ13LL4R3Q0WGRw1F+ng45vcihg511fStjaQipyJyIevk7AgHqH740dkyZIlLd3ejsi9bmZoW5cWbiJpaKeH0C3jkb0GKbw=="; }
        }
    }

    [global::System.Runtime.InteropServices.ComVisible(true)]
    [global::System.Runtime.InteropServices.Guid("e1d01a20-8ab0-4ba7-a527-e64f7fc83641")]
    [global::System.Runtime.InteropServices.InterfaceType(global::System.Runtime.InteropServices.ComInterfaceType.InterfaceIsDual)]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.0.0.0")]
    public interface IMyScript1KnowledgeScript
    {
        IKsResponse Execute();
        MyScript1Parameters Parameters { get; }

        void SetVersion(string version);
        void SetCounterValue(double counterValue);
        void SetExecCommandResult(string execCommandResult);
        void SetJobID(long jobId);
        void SetMachName(string name);
        void SetScriptInterval(long interval);
        void SetIterationCount(long iterationCount);

        void SetImportData(string data);
        void SetTempFileName(string fileName);
        void SetDynaCollectDataReturn(bool ret);
        void SetDynaDataLogReturn(bool ret);

        void SetAgentInfoProdType(string prodType);
        void SetAgentInfoAgtVer(string agtVer);
        void SetAgentInfoInstallDir(string installDir);
        void SetContextExReturn(string value);
        void SetContextExPropValue(string value);

        void SetSecurityContextReturn(bool value);
        void SetSecurityContextValue(string value);
        void SetMCEnterCSReturn(long value);
        void SetMCGetMOIDReturn(string value);
        void SetMCVersionValue(string value);
        void SetNQSleepReturn(long value);
    }

    [global::System.Runtime.InteropServices.ComVisible(true)]
    [global::System.Runtime.InteropServices.Guid("f12e97e1-a775-4f0d-80cb-b7006598f4f2")]
    [global::System.Runtime.InteropServices.ProgId("DNKS.powerShellKSSecurityConfigurationManager.MyScript1")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.0.0.0")]
    public sealed class MyScript1ScriptExecutor : BaseScriptExecutor<MyScript1, MyScript1Parameters, IMyScript1ParametersLocal, WindowsNqExt, IWindowsNqExt>, IMyScript1KnowledgeScript
    {
    }
}


