//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:1.4.2.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SdNcenter.Dnks.Parameters;
using SdNcenter.Dnks.Executors;
using SdNcenter.Dnks.KnowledgeScripts;
using SdNcenter.Dnks.Responses;
using SdNcenter.Dnks.ReportingTargets;
using SdNcenter.Dnks.PowerShell.KnowledgeScripts;

namespace powerShellKnowledgeScript1
{
    [global::System.Runtime.InteropServices.ComVisible(true)]
    [global::System.Runtime.InteropServices.Guid("4aa16a3b-36b9-426c-a6cb-ab34e2edd731")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.4.2.0")]
    public interface IAmazonCloudWatchParameters : IAmazonCloudWatchParametersLocal
    {
        [global::System.Runtime.InteropServices.DispId(1)]
        string EngineName { get; set; }
        [global::System.Runtime.InteropServices.DispId(2)]
        string AccessKey { get; set; }
        [global::System.Runtime.InteropServices.DispId(3)]
        string SecretKey { get; set; }

    }

    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.4.2.0")]
    public interface IAmazonCloudWatchParametersLocal
    {
        string EngineName { get; }
        string AccessKey { get; }
        string SecretKey { get; }

    }

    [global::System.Runtime.InteropServices.ComVisible(true)]
    [global::System.Runtime.InteropServices.Guid("1b6d7387-9dc4-4ac1-ad04-4f13beea6000")]
    [global::System.Runtime.InteropServices.ClassInterface(global::System.Runtime.InteropServices.ClassInterfaceType.None)]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.4.2.0")]
    public sealed class AmazonCloudWatchParameters : KSParameters, IAmazonCloudWatchParameters
    {
        public string EngineName { get; set; }
        public string AccessKey { get; set; }
        public string SecretKey { get; set; }

    }

    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.4.2.0")]
    public partial class AmazonCloudWatch : PowerShellKnowledgeScriptBase<AmazonCloudWatchParameters,IAmazonCloudWatchParametersLocal, WindowsNqExt, IWindowsNqExt>
    {
        protected override string LicenseData
        {
            get { return "MUzOtOkr0AJdcwV7yx0WOoH2W1p7pnyzv8q/vdfMIvzofV+CEUpnIAJiKidZ4i/ftpCH9STGvtVvsz8N+Ir58cuq3NZtY854RTG+CG4duQg="; }
        }
        
        protected override string DesKey
        {
            get { return "mG0kxQrJQFNQW6j9uX54or3tOVDt5CC+7AocOn2Obbn/vvZTE6u4Jgkiq3p2aHjO8TTaIe9TvUFR5eI1xcmWxP2dORprAuCEXR5ougQa1AOHUv/7ILc54rX6J8XuxkjXQuiEkj7h/utnaAstuxfLxXiGEGwjRsEzJHo1VFQJ3TXIoTIrdyiuSIrNaSR9FUxwIKwWHjX8WlMtkQckm2bUd/ZYET+bWIXSGC2/hcxDioujQH4XPAfPtkKU8wXLCcV51sKaa/ZNaSc24CbBEpxxfbbW5QR6mYdMl3d0fSvasGz0K+nGzes0ySQWOPmE2/OX2Kdoxg1BvN9IyKOWY3goiQ=="; }
        }

    }

    [global::System.Runtime.InteropServices.ComVisible(true)]
    [global::System.Runtime.InteropServices.Guid("6aa727de-de73-4caf-8042-2d3336d02815")]
    [global::System.Runtime.InteropServices.InterfaceType(global::System.Runtime.InteropServices.ComInterfaceType.InterfaceIsDual)]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.4.2.0")]
    public interface IAmazonCloudWatchKnowledgeScript
    {
        IKsResponse Execute();
        AmazonCloudWatchParameters Parameters { get; }

        void SetVersion(string version);
        void SetCounterValue(double counterValue);
        void SetExecCommandResult(string execCommandResult);
        void SetJobID(long jobId);
        void SetMachName(string name);
        void SetScriptInterval(long interval);
        void SetIterationCount(long iterationCount);

        void SetImportData(string data);
        void SetTempFileName(string fileName);
        void SetDynaCollectDataReturn(bool ret);
        void SetDynaDataLogReturn(bool ret);

        void SetAgentInfoProdType(string prodType);
        void SetAgentInfoAgtVer(string agtVer);
        void SetAgentInfoInstallDir(string installDir);
        void SetContextExReturn(string value);
        void SetContextExPropValue(string value);

        void SetSecurityContextReturn(bool value);
        void SetSecurityContextValue(string value);
        void SetMCEnterCSReturn(long value);
        void SetMCGetMOIDReturn(string value);
        void SetMCVersionValue(string value);
        void SetNQSleepReturn(long value);
    }

    [global::System.Runtime.InteropServices.ComVisible(true)]
    [global::System.Runtime.InteropServices.Guid("0d1c92a8-65eb-48ff-9ba2-a728229b4356")]
    [global::System.Runtime.InteropServices.ProgId("powerShellKnowledgeScript1.AmazonCloudWatch")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.4.2.0")]
    public sealed class AmazonCloudWatchScriptExecutor : BaseScriptExecutor<AmazonCloudWatch, AmazonCloudWatchParameters, IAmazonCloudWatchParametersLocal, WindowsNqExt, IWindowsNqExt>, IAmazonCloudWatchKnowledgeScript
    {
    }
}


