//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:1.4.2.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SdNcenter.Dnks.Parameters;
using SdNcenter.Dnks.Executors;
using SdNcenter.Dnks.KnowledgeScripts;
using SdNcenter.Dnks.Responses;
using SdNcenter.Dnks.ReportingTargets;
using SdNcenter.Dnks.PowerShell.KnowledgeScripts;

namespace powerShellKnowledgeScript1
{
    [global::System.Runtime.InteropServices.ComVisible(true)]
    [global::System.Runtime.InteropServices.Guid("3edadb84-e90c-4269-8237-cef620844d4c")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.4.2.0")]
    public interface IMyScript1Parameters : IMyScript1ParametersLocal
    {
        [global::System.Runtime.InteropServices.DispId(1)]
        string EngineName { get; set; }
        [global::System.Runtime.InteropServices.DispId(2)]
        string AccessKey { get; set; }
        [global::System.Runtime.InteropServices.DispId(3)]
        string SecretKey { get; set; }

    }

    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.4.2.0")]
    public interface IMyScript1ParametersLocal
    {
        string EngineName { get; }
        string AccessKey { get; }
        string SecretKey { get; }

    }

    [global::System.Runtime.InteropServices.ComVisible(true)]
    [global::System.Runtime.InteropServices.Guid("ce964a9c-06a6-4c2e-8fd3-a38437bf01b3")]
    [global::System.Runtime.InteropServices.ClassInterface(global::System.Runtime.InteropServices.ClassInterfaceType.None)]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.4.2.0")]
    public sealed class MyScript1Parameters : KSParameters, IMyScript1Parameters
    {
        public string EngineName { get; set; }
        public string AccessKey { get; set; }
        public string SecretKey { get; set; }

    }

    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.4.2.0")]
    public partial class MyScript1 : PowerShellKnowledgeScriptBase<MyScript1Parameters,IMyScript1ParametersLocal, WindowsNqExt, IWindowsNqExt>
    {
        protected override string LicenseData
        {
            get { return "Ilvn7/fgVZK3ID1L+YYyr3gpzcEbbZvDG9wAWb1vgwZ7/qp1i1WctpYM2KvqlNQUyUZmRGHdkG5eFeDwo5Qhq8SHoeHaas04"; }
        }
        
        protected override string DesKey
        {
            get { return "OW9B7nSB2m1dJR2lI5ibTFcggxWNeDC9A/lNKMxN+aMbmR/vKsGQy+XaqRfw/GkRsiZEDillKtckcha+DTCatuDjGsMFyYrThDjra/bpphglaL9VWWFeQZqvZD8JCr5ri+Lh41ocf4jNQFNNzx4/BUXNcYMOb0ZfaruMgEVLz0p/jmPQfC1ndY4Bq6AQsg/gdSgabx3eeFSIaNySVlf4LRVhMSrfqCXKWEkoZKCoUv57Ehz6xB1a99Bg3Ql12ryrcTb0KCi5f2Rm0S6DXOLOywx4SUD8se9zmZINJCUiWtegJ9HxXB6LTVutLv2amIUIjgKqUv+U4e9Iw2v66aeDcQ=="; }
        }

    }

    [global::System.Runtime.InteropServices.ComVisible(true)]
    [global::System.Runtime.InteropServices.Guid("027c1496-5847-4f80-8454-1483fa557226")]
    [global::System.Runtime.InteropServices.InterfaceType(global::System.Runtime.InteropServices.ComInterfaceType.InterfaceIsDual)]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.4.2.0")]
    public interface IMyScript1KnowledgeScript
    {
        IKsResponse Execute();
        MyScript1Parameters Parameters { get; }

        void SetVersion(string version);
        void SetCounterValue(double counterValue);
        void SetExecCommandResult(string execCommandResult);
        void SetJobID(long jobId);
        void SetMachName(string name);
        void SetScriptInterval(long interval);
        void SetIterationCount(long iterationCount);

        void SetImportData(string data);
        void SetTempFileName(string fileName);
        void SetDynaCollectDataReturn(bool ret);
        void SetDynaDataLogReturn(bool ret);

        void SetAgentInfoProdType(string prodType);
        void SetAgentInfoAgtVer(string agtVer);
        void SetAgentInfoInstallDir(string installDir);
        void SetContextExReturn(string value);
        void SetContextExPropValue(string value);

        void SetSecurityContextReturn(bool value);
        void SetSecurityContextValue(string value);
        void SetMCEnterCSReturn(long value);
        void SetMCGetMOIDReturn(string value);
        void SetMCVersionValue(string value);
        void SetNQSleepReturn(long value);
    }

    [global::System.Runtime.InteropServices.ComVisible(true)]
    [global::System.Runtime.InteropServices.Guid("407ec90c-8dd8-4e48-a3eb-dbd360460ca9")]
    [global::System.Runtime.InteropServices.ProgId("powerShellKnowledgeScript1.MyScript1")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("KsSettingsTool", "1.4.2.0")]
    public sealed class MyScript1ScriptExecutor : BaseScriptExecutor<MyScript1, MyScript1Parameters, IMyScript1ParametersLocal, WindowsNqExt, IWindowsNqExt>, IMyScript1KnowledgeScript
    {
    }
}


